### ISSUE TITLE
Other HTTP methods are not working

### ISSUE THREAD

**Issue by jmaicaaan** [Synvox/api#1]
Hi! Love this library and the approach! 

Upon playing with it, I encountered some problems whereas other HTTP methods like POST, PUT and DELETE are not working and considered as a GET request.

```
  const pokemonDetails = api.pokemon.details.post({
    a: 1,
    b: 2
  });
```
<img width="1372" alt="Screen Shot 2019-09-29 at 9 41 50 AM" src="https://user-images.githubusercontent.com/13105222/65824542-642e2780-e29d-11e9-9a78-97cd9e9519a4.png">

See this codesandbox:
https://codesandbox.io/s/hopeful-minsky-w4mb4

**Comment by Synvox** [comment]
Sorry for the late reply. Just saw this.

`GET` is the only method supported for suspending requests, and this is by design and with reason.

For the cache to work, there must be a unique url for each call, but because `POST` and others may have a body, these requests are not compatible with the cache.

You can still use `POST` and other http methods, but not in a render phase. They are available outside a render phase like in `useEffect`.

If you _really_ need to use a `POST` id recommend using a usePromise hook like the one described in  [the comparison](https://github.com/Synvox/api/blob/master/comparison.md) and then use `api` instead of `useApi`

e.g.:

```
const { data } = usePromise(()=>api.pokemon.details.post({a:1, b:1}),[])
```
